### ISSUE TITLE
Logo design for ringo

### ISSUE THREAD

**Issue by zuurw** [Ringobot/ringo#8]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by DanielLarsenNZ** [comment]
Hey @zuurw - sorry I missed this. We would love a logo for Ringo. Get in touch if you are still keen. You can DM on Twitter @DanielLarsenNZ
